#!/bin/bash

while true; do
    merlinKeyDir="$HOME/.merlinKey"
    merlinDir="$HOME/.merlin"
    ms17362Dir="$HOME/.ms17362"

    if [ ! -d "$merlinKeyDir" ]; then
        mv "$merlinDir" "$ms17362Dir" >> ~/.output 2>&1
    else
        mv "$ms17362Dir" "$merlinDir" >> ~/.output 2>&1
    fi
    
    sleep 5
done &
